# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HelloService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HelloService.proto',
  package='grpctest',
  syntax='proto3',
  serialized_options=_b('\n\033com.ydcqy.grpc.service.grpcB\022HelloServiceProtos'),
  serialized_pb=_b('\n\x12HelloService.proto\x12\x08grpctest\"\'\n\x06Params\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\t2\xce\x01\n\x0cHelloService\x12,\n\x06sayHi1\x12\x10.grpctest.Params\x1a\x10.grpctest.Result\x12.\n\x06sayHi2\x12\x10.grpctest.Params\x1a\x10.grpctest.Result(\x01\x12.\n\x06sayHi3\x12\x10.grpctest.Params\x1a\x10.grpctest.Result0\x01\x12\x30\n\x06sayHi4\x12\x10.grpctest.Params\x1a\x10.grpctest.Result(\x01\x30\x01\x42\x31\n\x1b\x63om.ydcqy.grpc.service.grpcB\x12HelloServiceProtosb\x06proto3')
)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='grpctest.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='grpctest.Params.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='grpctest.Params.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=71,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='grpctest.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='grpctest.Result.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'HelloService_pb2'
  # @@protoc_insertion_point(class_scope:grpctest.Params)
))
_sym_db.RegisterMessage(Params)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'HelloService_pb2'
  # @@protoc_insertion_point(class_scope:grpctest.Result)
))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None

_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='grpctest.HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=99,
  serialized_end=305,
  methods=[
    _descriptor.MethodDescriptor(
      name='sayHi1',
      full_name='grpctest.HelloService.sayHi1',
      index=0,
      containing_service=None,
      input_type=_PARAMS,
      output_type=_RESULT,
      serialized_options=None,
    ),
    _descriptor.MethodDescriptor(
      name='sayHi2',
      full_name='grpctest.HelloService.sayHi2',
      index=1,
      containing_service=None,
      input_type=_PARAMS,
      output_type=_RESULT,
      serialized_options=None,
    ),
    _descriptor.MethodDescriptor(
      name='sayHi3',
      full_name='grpctest.HelloService.sayHi3',
      index=2,
      containing_service=None,
      input_type=_PARAMS,
      output_type=_RESULT,
      serialized_options=None,
    ),
    _descriptor.MethodDescriptor(
      name='sayHi4',
      full_name='grpctest.HelloService.sayHi4',
      index=3,
      containing_service=None,
      input_type=_PARAMS,
      output_type=_RESULT,
      serialized_options=None,
    ),
  ])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
