server:
  port: 8201
spring:
  application:
    name: customer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+0800
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8100/eureka/
    registry-fetch-interval-seconds: 2