server:
  port: 8201
  tomcat:
    accept-count:
    max-threads:
spring:
  application:
    name: customer
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8100/eureka/
    registry-fetch-interval-seconds: 2