server:
  port: 8102

spring:
  profiles:
    active:
  application:
    name: @parent.artifactId@
  datasource:
    type:

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8100/eureka/


