server:
  port: 8101

spring:
  profiles:
    active:
  application:
    name: @parent.artifactId@
  datasource:
    type:

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8100/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1


