server:
  port: 8100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 2000
    response-cache-update-interval-ms: 2000
    response-cache-auto-expiration-in-seconds: 2
#    enable-self-preservation: false


