cluster:
  type: none
  nodes:
   - host: 10.1.7.11
     port: 6379
minIdle: 10
maxIdle: 20
maxTotal: 500
maxWaitMillis: 5000
minEvictableIdleTimeMillis: 30000
timeBetweenEvictionRunsMillis: 100000
testWhileIdle: true
testOnBorrow: false
testOnReturn: false
