server:
  port: 8101

spring:
  profiles:
    active:
  application:
    name: @parent.artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://g1.ydcqy.com:13106/personal_item?useSSL=false
    username: select_pit
    password: 2gBc6zAQ22AG
    initial-size: 10
    min-idle: 10
    max-active: 500
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 30000
    validation-query: select 1
    test-on-return: false
    test-while-idle: true
    test-on-borrow: true
    filters: stat,wall,log4j

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8100/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
