server:
  port: 8101

spring:
  profiles:
    active:
#  application:
#    name: @parent.artifactId@
  ########## 数据源配置 ###########
  datasource:
    personalItem:
      type: com.alibaba.druid.producerPool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.1.7.11:13106/yuanda?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: pit_all
      password: ieNgeiVaqua2
      initialSize: 10
      minIdle: 10
      maxActive: 500
      maxWait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testOnReturn: false
      testWhileIdle: true
      testOnBorrow: true
      filters: stat,wall,log4j
    g1:
      type: com.alibaba.druid.producerPool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://g1.ydcqy.com:13106/personal_item?useSSL=false&characterEncoding=UTF-8
      username: root
      password: zxnNbxS0KpWl
      initialSize: 10
      minIdle: 10
      maxActive: 500
      maxWait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testOnReturn: false
      testWhileIdle: true
      testOnBorrow: true
      filters: stat,wall,log4j


  #################################
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://localhost:8100/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1

  #
  ########### MyBatis配置 ###########
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration-properties:
pagehelper:
  helper-dialect: mysql

logging:
  level:
endpoints:
  autoconfig:
    enabled: true
  mappings:
    enabled: true
  metrics:
    enabled: true
management:
  security:
    enabled: false
#    root: debug
#    com.ydcqy.cloud.services.talk.dao : debug
