server:
  port: 8102

spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    news:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://ip:port/db
      username: username
      password: pwd
      initial-size: 10
      min-idle: 10
      max-active: 500
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-on-return: false
      test-while-idle: true
      test-on-borrow: true
      filters: stat,wall,log4j
    shopItem:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 500
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      filters: stat,wall,log4j
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8