server:
  port: 8101


ydcqy:
  grpc:
    server:
      port: 8111
      thread-num: 200
spring:
  redis:
    url: redis://10.1.7.11:6379
  data:
    mongodb:
      host: 10.1.7.21
      port: 27017
      database: yuanda
